# themes from https://github.com/alacritty/alacritty-theme

# import = ["~/.config/alacritty/themes/solarized_osaka.toml"]
# import = ["~/.config/alacritty/themes/challenger_deep.toml"]
import = ["~/.config/alacritty/themes/nightfly.toml"]

[font]
size = 20

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"
opacity = 0.8
blur = true

[window.padding]
x = 8
y = 8

[scrolling]
# The number of lines the scrollback buffer should scroll
history = 10000
# Multiplier for scrolling speed
multiplier = 3

[mouse]
# Whether to enable the mouse support in Alacritty.
# enabled = true

# Shell and launch commands
[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login", "-c", "tmux a -t base || tmux new -s base"]
