# themes from https://github.com/alacritty/alacritty-theme

# import = ["~/.config/alacritty/themes/solarized_osaka.toml"]
# import = ["~/.config/alacritty/themes/challenger_deep.toml"]
import = ["~/.config/alacritty/themes/nightfly.toml"]

[font]
size = 20

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "ZedMono Nerd Font"

[window]
decorations = "none"
opacity = 1
blur = true

[window.padding]
x = 6
y = 6

# FIX: This was supposed to stop command scrolling at the prompt and allow scrolling of history buffer instead, but it's not
[scrolling]
history = 0

# Shell and launch commands
[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login", "-c", "tmux a -t base || tmux new -s base"]
